name: Build and Push Docker Image

env:
  PHP_VERSIONS: 8.0 8.1 8.2 8.3 8.4

on:
  push:
    # Run on push to the master branch
    branches:
      - master
  schedule:
    # Run every Monday at 01:00
    - cron: '0 1 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          for version in $PHP_VERSIONS; do
            docker build --build-arg PHP_VERSION=$version -t ghcr.io/${{ github.repository }}:$version --push .
          done
